// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZfiqUijllGNKEWMl7Cbpltj7B7quECw',
    appId: '1:345667526823:web:04d9936bae5d7f51bcfb82',
    messagingSenderId: '345667526823',
    projectId: 'bspassist-2d419',
    authDomain: 'bspassist-2d419.firebaseapp.com',
    storageBucket: 'bspassist-2d419.appspot.com',
    measurementId: 'G-XTC8YHSJT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKocPfGgohYh226xtSYK064oDbFDTML4w',
    appId: '1:345667526823:android:809491364d6471d8bcfb82',
    messagingSenderId: '345667526823',
    projectId: 'bspassist-2d419',
    storageBucket: 'bspassist-2d419.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnAK9N4qtyewMxPNHs1PNscpmGvcUfwrI',
    appId: '1:345667526823:ios:2e668fa32d7e3fc7bcfb82',
    messagingSenderId: '345667526823',
    projectId: 'bspassist-2d419',
    storageBucket: 'bspassist-2d419.appspot.com',
    iosClientId: '345667526823-ken231m86qbcpngjje8kfh92jqu9suij.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnAK9N4qtyewMxPNHs1PNscpmGvcUfwrI',
    appId: '1:345667526823:ios:6586ab8e3605fee5bcfb82',
    messagingSenderId: '345667526823',
    projectId: 'bspassist-2d419',
    storageBucket: 'bspassist-2d419.appspot.com',
    iosClientId: '345667526823-c95veo7pvo1fo9st9t2f7hg2s6h3gdch.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
